version: "2"
run:
  timeout: 3m
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - errcheck
    - ineffassign
    - makezero
    - staticcheck
    - asciicheck
  settings:
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
  exclusions:
    generated: lax
    paths:
      - migrations
      - docs
      - third_party$
formatters:
  enable:
    - gci
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - prefix(courier-service)
  exclusions:
    generated: lax
    paths:
      - migrations
      - api
      - assets
      - githooks
      - .github
      - proto 
      - scripts 
      - testdata
      - third_party$