// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "courier-service/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockсourierRepository is a mock of сourierRepository interface.
type MockсourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockсourierRepositoryMockRecorder
}

// MockсourierRepositoryMockRecorder is the mock recorder for MockсourierRepository.
type MockсourierRepositoryMockRecorder struct {
	mock *MockсourierRepository
}

// NewMockсourierRepository creates a new mock instance.
func NewMockсourierRepository(ctrl *gomock.Controller) *MockсourierRepository {
	mock := &MockсourierRepository{ctrl: ctrl}
	mock.recorder = &MockсourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockсourierRepository) EXPECT() *MockсourierRepositoryMockRecorder {
	return m.recorder
}

// CreateCourier mocks base method.
func (m *MockсourierRepository) CreateCourier(ctx context.Context, courier model.Courier) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourier", ctx, courier)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCourier indicates an expected call of CreateCourier.
func (mr *MockсourierRepositoryMockRecorder) CreateCourier(ctx, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourier", reflect.TypeOf((*MockсourierRepository)(nil).CreateCourier), ctx, courier)
}

// ExistsCourierByPhone mocks base method.
func (m *MockсourierRepository) ExistsCourierByPhone(ctx context.Context, phone string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsCourierByPhone", ctx, phone)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsCourierByPhone indicates an expected call of ExistsCourierByPhone.
func (mr *MockсourierRepositoryMockRecorder) ExistsCourierByPhone(ctx, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsCourierByPhone", reflect.TypeOf((*MockсourierRepository)(nil).ExistsCourierByPhone), ctx, phone)
}

// FindAvailableCourier mocks base method.
func (m *MockсourierRepository) FindAvailableCourier(ctx context.Context) (model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailableCourier", ctx)
	ret0, _ := ret[0].(model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailableCourier indicates an expected call of FindAvailableCourier.
func (mr *MockсourierRepositoryMockRecorder) FindAvailableCourier(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailableCourier", reflect.TypeOf((*MockсourierRepository)(nil).FindAvailableCourier), ctx)
}

// FreeCouriersWithInterval mocks base method.
func (m *MockсourierRepository) FreeCouriersWithInterval(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FreeCouriersWithInterval", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FreeCouriersWithInterval indicates an expected call of FreeCouriersWithInterval.
func (mr *MockсourierRepositoryMockRecorder) FreeCouriersWithInterval(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FreeCouriersWithInterval", reflect.TypeOf((*MockсourierRepository)(nil).FreeCouriersWithInterval), ctx)
}

// GetAllCouriers mocks base method.
func (m *MockсourierRepository) GetAllCouriers(ctx context.Context) ([]model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCouriers", ctx)
	ret0, _ := ret[0].([]model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCouriers indicates an expected call of GetAllCouriers.
func (mr *MockсourierRepositoryMockRecorder) GetAllCouriers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCouriers", reflect.TypeOf((*MockсourierRepository)(nil).GetAllCouriers), ctx)
}

// GetCourierById mocks base method.
func (m *MockсourierRepository) GetCourierById(ctx context.Context, id int64) (model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierById", ctx, id)
	ret0, _ := ret[0].(model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierById indicates an expected call of GetCourierById.
func (mr *MockсourierRepositoryMockRecorder) GetCourierById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierById", reflect.TypeOf((*MockсourierRepository)(nil).GetCourierById), ctx, id)
}

// UpdateCourier mocks base method.
func (m *MockсourierRepository) UpdateCourier(ctx context.Context, courier model.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourier", ctx, courier)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourier indicates an expected call of UpdateCourier.
func (mr *MockсourierRepositoryMockRecorder) UpdateCourier(ctx, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourier", reflect.TypeOf((*MockсourierRepository)(nil).UpdateCourier), ctx, courier)
}

// MockdeliveryRepository is a mock of deliveryRepository interface.
type MockdeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryRepositoryMockRecorder
}

// MockdeliveryRepositoryMockRecorder is the mock recorder for MockdeliveryRepository.
type MockdeliveryRepositoryMockRecorder struct {
	mock *MockdeliveryRepository
}

// NewMockdeliveryRepository creates a new mock instance.
func NewMockdeliveryRepository(ctrl *gomock.Controller) *MockdeliveryRepository {
	mock := &MockdeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockdeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryRepository) EXPECT() *MockdeliveryRepositoryMockRecorder {
	return m.recorder
}

// CouriersDelivery mocks base method.
func (m *MockdeliveryRepository) CouriersDelivery(ctx context.Context, orderID string) (model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CouriersDelivery", ctx, orderID)
	ret0, _ := ret[0].(model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CouriersDelivery indicates an expected call of CouriersDelivery.
func (mr *MockdeliveryRepositoryMockRecorder) CouriersDelivery(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CouriersDelivery", reflect.TypeOf((*MockdeliveryRepository)(nil).CouriersDelivery), ctx, orderID)
}

// CreateDelivery mocks base method.
func (m *MockdeliveryRepository) CreateDelivery(ctx context.Context, delivery model.Delivery) (model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDelivery", ctx, delivery)
	ret0, _ := ret[0].(model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDelivery indicates an expected call of CreateDelivery.
func (mr *MockdeliveryRepositoryMockRecorder) CreateDelivery(ctx, delivery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDelivery", reflect.TypeOf((*MockdeliveryRepository)(nil).CreateDelivery), ctx, delivery)
}

// DeleteDelivery mocks base method.
func (m *MockdeliveryRepository) DeleteDelivery(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDelivery", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDelivery indicates an expected call of DeleteDelivery.
func (mr *MockdeliveryRepositoryMockRecorder) DeleteDelivery(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDelivery", reflect.TypeOf((*MockdeliveryRepository)(nil).DeleteDelivery), ctx, orderID)
}

// MocktxRunner is a mock of txRunner interface.
type MocktxRunner struct {
	ctrl     *gomock.Controller
	recorder *MocktxRunnerMockRecorder
}

// MocktxRunnerMockRecorder is the mock recorder for MocktxRunner.
type MocktxRunnerMockRecorder struct {
	mock *MocktxRunner
}

// NewMocktxRunner creates a new mock instance.
func NewMocktxRunner(ctrl *gomock.Controller) *MocktxRunner {
	mock := &MocktxRunner{ctrl: ctrl}
	mock.recorder = &MocktxRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktxRunner) EXPECT() *MocktxRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MocktxRunner) Run(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MocktxRunnerMockRecorder) Run(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MocktxRunner)(nil).Run), ctx, fn)
}
