// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package processor_test is a generated GoMock package.
package processor_test

import (
	context "context"
	assign "courier-service/internal/usecase/delivery/assign"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockassignUseCase is a mock of assignUseCase interface.
type MockassignUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockassignUseCaseMockRecorder
}

// MockassignUseCaseMockRecorder is the mock recorder for MockassignUseCase.
type MockassignUseCaseMockRecorder struct {
	mock *MockassignUseCase
}

// NewMockassignUseCase creates a new mock instance.
func NewMockassignUseCase(ctrl *gomock.Controller) *MockassignUseCase {
	mock := &MockassignUseCase{ctrl: ctrl}
	mock.recorder = &MockassignUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockassignUseCase) EXPECT() *MockassignUseCaseMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockassignUseCase) Assign(ctx context.Context, OrderID string) (assign.DeliveryAssignResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", ctx, OrderID)
	ret0, _ := ret[0].(assign.DeliveryAssignResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assign indicates an expected call of Assign.
func (mr *MockassignUseCaseMockRecorder) Assign(ctx, OrderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockassignUseCase)(nil).Assign), ctx, OrderID)
}

// MockunassignUseCase is a mock of unassignUseCase interface.
type MockunassignUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockunassignUseCaseMockRecorder
}

// MockunassignUseCaseMockRecorder is the mock recorder for MockunassignUseCase.
type MockunassignUseCaseMockRecorder struct {
	mock *MockunassignUseCase
}

// NewMockunassignUseCase creates a new mock instance.
func NewMockunassignUseCase(ctrl *gomock.Controller) *MockunassignUseCase {
	mock := &MockunassignUseCase{ctrl: ctrl}
	mock.recorder = &MockunassignUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockunassignUseCase) EXPECT() *MockunassignUseCaseMockRecorder {
	return m.recorder
}

// Unassign mocks base method.
func (m *MockunassignUseCase) Unassign(ctx context.Context, OrderID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unassign", ctx, OrderID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unassign indicates an expected call of Unassign.
func (mr *MockunassignUseCaseMockRecorder) Unassign(ctx, OrderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unassign", reflect.TypeOf((*MockunassignUseCase)(nil).Unassign), ctx, OrderID)
}

// MockcompleteUseCase is a mock of completeUseCase interface.
type MockcompleteUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockcompleteUseCaseMockRecorder
}

// MockcompleteUseCaseMockRecorder is the mock recorder for MockcompleteUseCase.
type MockcompleteUseCaseMockRecorder struct {
	mock *MockcompleteUseCase
}

// NewMockcompleteUseCase creates a new mock instance.
func NewMockcompleteUseCase(ctrl *gomock.Controller) *MockcompleteUseCase {
	mock := &MockcompleteUseCase{ctrl: ctrl}
	mock.recorder = &MockcompleteUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompleteUseCase) EXPECT() *MockcompleteUseCaseMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockcompleteUseCase) Complete(ctx context.Context, OrderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, OrderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockcompleteUseCaseMockRecorder) Complete(ctx, OrderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockcompleteUseCase)(nil).Complete), ctx, OrderID)
}
