// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package courier_test is a generated GoMock package.
package courier_test

import (
	context "context"
	model "courier-service/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockcourierUseCase is a mock of courierUseCase interface.
type MockcourierUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockcourierUseCaseMockRecorder
}

// MockcourierUseCaseMockRecorder is the mock recorder for MockcourierUseCase.
type MockcourierUseCaseMockRecorder struct {
	mock *MockcourierUseCase
}

// NewMockcourierUseCase creates a new mock instance.
func NewMockcourierUseCase(ctrl *gomock.Controller) *MockcourierUseCase {
	mock := &MockcourierUseCase{ctrl: ctrl}
	mock.recorder = &MockcourierUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourierUseCase) EXPECT() *MockcourierUseCaseMockRecorder {
	return m.recorder
}

// CreateCourier mocks base method.
func (m *MockcourierUseCase) CreateCourier(ctx context.Context, courier model.Courier) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourier", ctx, courier)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCourier indicates an expected call of CreateCourier.
func (mr *MockcourierUseCaseMockRecorder) CreateCourier(ctx, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourier", reflect.TypeOf((*MockcourierUseCase)(nil).CreateCourier), ctx, courier)
}

// GetAllCouriers mocks base method.
func (m *MockcourierUseCase) GetAllCouriers(ctx context.Context) ([]model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCouriers", ctx)
	ret0, _ := ret[0].([]model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCouriers indicates an expected call of GetAllCouriers.
func (mr *MockcourierUseCaseMockRecorder) GetAllCouriers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCouriers", reflect.TypeOf((*MockcourierUseCase)(nil).GetAllCouriers), ctx)
}

// GetCourierById mocks base method.
func (m *MockcourierUseCase) GetCourierById(ctx context.Context, id int64) (model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierById", ctx, id)
	ret0, _ := ret[0].(model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierById indicates an expected call of GetCourierById.
func (mr *MockcourierUseCaseMockRecorder) GetCourierById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierById", reflect.TypeOf((*MockcourierUseCase)(nil).GetCourierById), ctx, id)
}

// UpdateCourier mocks base method.
func (m *MockcourierUseCase) UpdateCourier(ctx context.Context, courier model.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourier", ctx, courier)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourier indicates an expected call of UpdateCourier.
func (mr *MockcourierUseCaseMockRecorder) UpdateCourier(ctx, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourier", reflect.TypeOf((*MockcourierUseCase)(nil).UpdateCourier), ctx, courier)
}
