// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package delivery_test is a generated GoMock package.
package delivery_test

import (
	context "context"
	assign "courier-service/internal/usecase/delivery/assign"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockassignUsecase is a mock of assignUsecase interface.
type MockassignUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockassignUsecaseMockRecorder
}

// MockassignUsecaseMockRecorder is the mock recorder for MockassignUsecase.
type MockassignUsecaseMockRecorder struct {
	mock *MockassignUsecase
}

// NewMockassignUsecase creates a new mock instance.
func NewMockassignUsecase(ctrl *gomock.Controller) *MockassignUsecase {
	mock := &MockassignUsecase{ctrl: ctrl}
	mock.recorder = &MockassignUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockassignUsecase) EXPECT() *MockassignUsecaseMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockassignUsecase) Assign(arg0 context.Context, arg1 string) (assign.DeliveryAssignResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", arg0, arg1)
	ret0, _ := ret[0].(assign.DeliveryAssignResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assign indicates an expected call of Assign.
func (mr *MockassignUsecaseMockRecorder) Assign(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockassignUsecase)(nil).Assign), arg0, arg1)
}

// MockunassignUsecase is a mock of unassignUsecase interface.
type MockunassignUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockunassignUsecaseMockRecorder
}

// MockunassignUsecaseMockRecorder is the mock recorder for MockunassignUsecase.
type MockunassignUsecaseMockRecorder struct {
	mock *MockunassignUsecase
}

// NewMockunassignUsecase creates a new mock instance.
func NewMockunassignUsecase(ctrl *gomock.Controller) *MockunassignUsecase {
	mock := &MockunassignUsecase{ctrl: ctrl}
	mock.recorder = &MockunassignUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockunassignUsecase) EXPECT() *MockunassignUsecaseMockRecorder {
	return m.recorder
}

// Unassign mocks base method.
func (m *MockunassignUsecase) Unassign(arg0 context.Context, arg1 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unassign", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unassign indicates an expected call of Unassign.
func (mr *MockunassignUsecaseMockRecorder) Unassign(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unassign", reflect.TypeOf((*MockunassignUsecase)(nil).Unassign), arg0, arg1)
}
