// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package assign_test is a generated GoMock package.
package assign_test

import (
	context "context"
	model "courier-service/internal/model"
	assign "courier-service/internal/usecase/delivery/assign"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockcourierRepository is a mock of courierRepository interface.
type MockcourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockcourierRepositoryMockRecorder
}

// MockcourierRepositoryMockRecorder is the mock recorder for MockcourierRepository.
type MockcourierRepositoryMockRecorder struct {
	mock *MockcourierRepository
}

// NewMockcourierRepository creates a new mock instance.
func NewMockcourierRepository(ctrl *gomock.Controller) *MockcourierRepository {
	mock := &MockcourierRepository{ctrl: ctrl}
	mock.recorder = &MockcourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourierRepository) EXPECT() *MockcourierRepositoryMockRecorder {
	return m.recorder
}

// CreateCourier mocks base method.
func (m *MockcourierRepository) CreateCourier(ctx context.Context, courier model.Courier) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourier", ctx, courier)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCourier indicates an expected call of CreateCourier.
func (mr *MockcourierRepositoryMockRecorder) CreateCourier(ctx, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourier", reflect.TypeOf((*MockcourierRepository)(nil).CreateCourier), ctx, courier)
}

// ExistsCourierByPhone mocks base method.
func (m *MockcourierRepository) ExistsCourierByPhone(ctx context.Context, phone string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsCourierByPhone", ctx, phone)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsCourierByPhone indicates an expected call of ExistsCourierByPhone.
func (mr *MockcourierRepositoryMockRecorder) ExistsCourierByPhone(ctx, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsCourierByPhone", reflect.TypeOf((*MockcourierRepository)(nil).ExistsCourierByPhone), ctx, phone)
}

// FindAvailableCourier mocks base method.
func (m *MockcourierRepository) FindAvailableCourier(ctx context.Context) (model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailableCourier", ctx)
	ret0, _ := ret[0].(model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailableCourier indicates an expected call of FindAvailableCourier.
func (mr *MockcourierRepositoryMockRecorder) FindAvailableCourier(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailableCourier", reflect.TypeOf((*MockcourierRepository)(nil).FindAvailableCourier), ctx)
}

// FreeCouriersWithInterval mocks base method.
func (m *MockcourierRepository) FreeCouriersWithInterval(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FreeCouriersWithInterval", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FreeCouriersWithInterval indicates an expected call of FreeCouriersWithInterval.
func (mr *MockcourierRepositoryMockRecorder) FreeCouriersWithInterval(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FreeCouriersWithInterval", reflect.TypeOf((*MockcourierRepository)(nil).FreeCouriersWithInterval), ctx)
}

// GetAllCouriers mocks base method.
func (m *MockcourierRepository) GetAllCouriers(ctx context.Context) ([]model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCouriers", ctx)
	ret0, _ := ret[0].([]model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCouriers indicates an expected call of GetAllCouriers.
func (mr *MockcourierRepositoryMockRecorder) GetAllCouriers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCouriers", reflect.TypeOf((*MockcourierRepository)(nil).GetAllCouriers), ctx)
}

// GetCourierById mocks base method.
func (m *MockcourierRepository) GetCourierById(ctx context.Context, id int64) (model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierById", ctx, id)
	ret0, _ := ret[0].(model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierById indicates an expected call of GetCourierById.
func (mr *MockcourierRepositoryMockRecorder) GetCourierById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierById", reflect.TypeOf((*MockcourierRepository)(nil).GetCourierById), ctx, id)
}

// GetCourierIDByOrderID mocks base method.
func (m *MockcourierRepository) GetCourierIDByOrderID(ctx context.Context, orderID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierIDByOrderID", ctx, orderID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierIDByOrderID indicates an expected call of GetCourierIDByOrderID.
func (mr *MockcourierRepositoryMockRecorder) GetCourierIDByOrderID(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierIDByOrderID", reflect.TypeOf((*MockcourierRepository)(nil).GetCourierIDByOrderID), ctx, orderID)
}

// UpdateCourier mocks base method.
func (m *MockcourierRepository) UpdateCourier(ctx context.Context, courier model.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourier", ctx, courier)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourier indicates an expected call of UpdateCourier.
func (mr *MockcourierRepositoryMockRecorder) UpdateCourier(ctx, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourier", reflect.TypeOf((*MockcourierRepository)(nil).UpdateCourier), ctx, courier)
}

// MockdeliveryRepository is a mock of deliveryRepository interface.
type MockdeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryRepositoryMockRecorder
}

// MockdeliveryRepositoryMockRecorder is the mock recorder for MockdeliveryRepository.
type MockdeliveryRepositoryMockRecorder struct {
	mock *MockdeliveryRepository
}

// NewMockdeliveryRepository creates a new mock instance.
func NewMockdeliveryRepository(ctrl *gomock.Controller) *MockdeliveryRepository {
	mock := &MockdeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockdeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryRepository) EXPECT() *MockdeliveryRepositoryMockRecorder {
	return m.recorder
}

// CouriersDelivery mocks base method.
func (m *MockdeliveryRepository) CouriersDelivery(ctx context.Context, orderID string) (model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CouriersDelivery", ctx, orderID)
	ret0, _ := ret[0].(model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CouriersDelivery indicates an expected call of CouriersDelivery.
func (mr *MockdeliveryRepositoryMockRecorder) CouriersDelivery(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CouriersDelivery", reflect.TypeOf((*MockdeliveryRepository)(nil).CouriersDelivery), ctx, orderID)
}

// CreateDelivery mocks base method.
func (m *MockdeliveryRepository) CreateDelivery(ctx context.Context, delivery model.Delivery) (model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDelivery", ctx, delivery)
	ret0, _ := ret[0].(model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDelivery indicates an expected call of CreateDelivery.
func (mr *MockdeliveryRepositoryMockRecorder) CreateDelivery(ctx, delivery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDelivery", reflect.TypeOf((*MockdeliveryRepository)(nil).CreateDelivery), ctx, delivery)
}

// DeleteDelivery mocks base method.
func (m *MockdeliveryRepository) DeleteDelivery(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDelivery", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDelivery indicates an expected call of DeleteDelivery.
func (mr *MockdeliveryRepositoryMockRecorder) DeleteDelivery(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDelivery", reflect.TypeOf((*MockdeliveryRepository)(nil).DeleteDelivery), ctx, orderID)
}

// MocktxRunner is a mock of txRunner interface.
type MocktxRunner struct {
	ctrl     *gomock.Controller
	recorder *MocktxRunnerMockRecorder
}

// MocktxRunnerMockRecorder is the mock recorder for MocktxRunner.
type MocktxRunnerMockRecorder struct {
	mock *MocktxRunner
}

// NewMocktxRunner creates a new mock instance.
func NewMocktxRunner(ctrl *gomock.Controller) *MocktxRunner {
	mock := &MocktxRunner{ctrl: ctrl}
	mock.recorder = &MocktxRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktxRunner) EXPECT() *MocktxRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MocktxRunner) Run(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MocktxRunnerMockRecorder) Run(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MocktxRunner)(nil).Run), ctx, fn)
}

// MockdeliveryCalculatorFactory is a mock of deliveryCalculatorFactory interface.
type MockdeliveryCalculatorFactory struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryCalculatorFactoryMockRecorder
}

// MockdeliveryCalculatorFactoryMockRecorder is the mock recorder for MockdeliveryCalculatorFactory.
type MockdeliveryCalculatorFactoryMockRecorder struct {
	mock *MockdeliveryCalculatorFactory
}

// NewMockdeliveryCalculatorFactory creates a new mock instance.
func NewMockdeliveryCalculatorFactory(ctrl *gomock.Controller) *MockdeliveryCalculatorFactory {
	mock := &MockdeliveryCalculatorFactory{ctrl: ctrl}
	mock.recorder = &MockdeliveryCalculatorFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryCalculatorFactory) EXPECT() *MockdeliveryCalculatorFactoryMockRecorder {
	return m.recorder
}

// GetDeliveryCalculator mocks base method.
func (m *MockdeliveryCalculatorFactory) GetDeliveryCalculator(courierType model.CourierTransportType) assign.DeliveryCalculator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliveryCalculator", courierType)
	ret0, _ := ret[0].(assign.DeliveryCalculator)
	return ret0
}

// GetDeliveryCalculator indicates an expected call of GetDeliveryCalculator.
func (mr *MockdeliveryCalculatorFactoryMockRecorder) GetDeliveryCalculator(courierType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliveryCalculator", reflect.TypeOf((*MockdeliveryCalculatorFactory)(nil).GetDeliveryCalculator), courierType)
}
