// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handlers/contract.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "courier-service/internal/model"
	usecase "courier-service/internal/usecase"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockсourierUseCase is a mock of сourierUseCase interface.
type MockсourierUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockсourierUseCaseMockRecorder
}

// MockсourierUseCaseMockRecorder is the mock recorder for MockсourierUseCase.
type MockсourierUseCaseMockRecorder struct {
	mock *MockсourierUseCase
}

// NewMockсourierUseCase creates a new mock instance.
func NewMockсourierUseCase(ctrl *gomock.Controller) *MockсourierUseCase {
	mock := &MockсourierUseCase{ctrl: ctrl}
	mock.recorder = &MockсourierUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockсourierUseCase) EXPECT() *MockсourierUseCaseMockRecorder {
	return m.recorder
}

// CreateCourier mocks base method.
func (m *MockсourierUseCase) CreateCourier(ctx context.Context, courier model.Courier) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourier", ctx, courier)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCourier indicates an expected call of CreateCourier.
func (mr *MockсourierUseCaseMockRecorder) CreateCourier(ctx, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourier", reflect.TypeOf((*MockсourierUseCase)(nil).CreateCourier), ctx, courier)
}

// GetAllCouriers mocks base method.
func (m *MockсourierUseCase) GetAllCouriers(ctx context.Context) ([]model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCouriers", ctx)
	ret0, _ := ret[0].([]model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCouriers indicates an expected call of GetAllCouriers.
func (mr *MockсourierUseCaseMockRecorder) GetAllCouriers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCouriers", reflect.TypeOf((*MockсourierUseCase)(nil).GetAllCouriers), ctx)
}

// GetCourierById mocks base method.
func (m *MockсourierUseCase) GetCourierById(ctx context.Context, id int64) (model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierById", ctx, id)
	ret0, _ := ret[0].(model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierById indicates an expected call of GetCourierById.
func (mr *MockсourierUseCaseMockRecorder) GetCourierById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierById", reflect.TypeOf((*MockсourierUseCase)(nil).GetCourierById), ctx, id)
}

// UpdateCourier mocks base method.
func (m *MockсourierUseCase) UpdateCourier(ctx context.Context, courier model.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourier", ctx, courier)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourier indicates an expected call of UpdateCourier.
func (mr *MockсourierUseCaseMockRecorder) UpdateCourier(ctx, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourier", reflect.TypeOf((*MockсourierUseCase)(nil).UpdateCourier), ctx, courier)
}

// MockdeliveryUseCase is a mock of deliveryUseCase interface.
type MockdeliveryUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryUseCaseMockRecorder
}

// MockdeliveryUseCaseMockRecorder is the mock recorder for MockdeliveryUseCase.
type MockdeliveryUseCaseMockRecorder struct {
	mock *MockdeliveryUseCase
}

// NewMockdeliveryUseCase creates a new mock instance.
func NewMockdeliveryUseCase(ctrl *gomock.Controller) *MockdeliveryUseCase {
	mock := &MockdeliveryUseCase{ctrl: ctrl}
	mock.recorder = &MockdeliveryUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryUseCase) EXPECT() *MockdeliveryUseCaseMockRecorder {
	return m.recorder
}

// AssignDelivery mocks base method.
func (m *MockdeliveryUseCase) AssignDelivery(ctx context.Context, req usecase.DeliveryAssignRequest) (usecase.DeliveryAssignResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignDelivery", ctx, req)
	ret0, _ := ret[0].(usecase.DeliveryAssignResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignDelivery indicates an expected call of AssignDelivery.
func (mr *MockdeliveryUseCaseMockRecorder) AssignDelivery(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignDelivery", reflect.TypeOf((*MockdeliveryUseCase)(nil).AssignDelivery), ctx, req)
}

// UnassignDelivery mocks base method.
func (m *MockdeliveryUseCase) UnassignDelivery(ctx context.Context, req usecase.DeliveryUnassignRequest) (usecase.DeliveryUnassignResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignDelivery", ctx, req)
	ret0, _ := ret[0].(usecase.DeliveryUnassignResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignDelivery indicates an expected call of UnassignDelivery.
func (mr *MockdeliveryUseCaseMockRecorder) UnassignDelivery(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignDelivery", reflect.TypeOf((*MockdeliveryUseCase)(nil).UnassignDelivery), ctx, req)
}
