// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package courier_test is a generated GoMock package.
package courier_test

import (
	context "context"
	model "courier-service/internal/model"
	courier "courier-service/internal/usecase/courier"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockcourierRepository is a mock of courierRepository interface.
type MockcourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockcourierRepositoryMockRecorder
}

// MockcourierRepositoryMockRecorder is the mock recorder for MockcourierRepository.
type MockcourierRepositoryMockRecorder struct {
	mock *MockcourierRepository
}

// NewMockcourierRepository creates a new mock instance.
func NewMockcourierRepository(ctrl *gomock.Controller) *MockcourierRepository {
	mock := &MockcourierRepository{ctrl: ctrl}
	mock.recorder = &MockcourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourierRepository) EXPECT() *MockcourierRepositoryMockRecorder {
	return m.recorder
}

// CreateCourier mocks base method.
func (m *MockcourierRepository) CreateCourier(ctx context.Context, courier model.Courier) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourier", ctx, courier)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCourier indicates an expected call of CreateCourier.
func (mr *MockcourierRepositoryMockRecorder) CreateCourier(ctx, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourier", reflect.TypeOf((*MockcourierRepository)(nil).CreateCourier), ctx, courier)
}

// ExistsCourierByPhone mocks base method.
func (m *MockcourierRepository) ExistsCourierByPhone(ctx context.Context, phone string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsCourierByPhone", ctx, phone)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsCourierByPhone indicates an expected call of ExistsCourierByPhone.
func (mr *MockcourierRepositoryMockRecorder) ExistsCourierByPhone(ctx, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsCourierByPhone", reflect.TypeOf((*MockcourierRepository)(nil).ExistsCourierByPhone), ctx, phone)
}

// FindAvailableCourier mocks base method.
func (m *MockcourierRepository) FindAvailableCourier(ctx context.Context) (model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailableCourier", ctx)
	ret0, _ := ret[0].(model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailableCourier indicates an expected call of FindAvailableCourier.
func (mr *MockcourierRepositoryMockRecorder) FindAvailableCourier(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailableCourier", reflect.TypeOf((*MockcourierRepository)(nil).FindAvailableCourier), ctx)
}

// FreeCouriersWithInterval mocks base method.
func (m *MockcourierRepository) FreeCouriersWithInterval(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FreeCouriersWithInterval", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FreeCouriersWithInterval indicates an expected call of FreeCouriersWithInterval.
func (mr *MockcourierRepositoryMockRecorder) FreeCouriersWithInterval(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FreeCouriersWithInterval", reflect.TypeOf((*MockcourierRepository)(nil).FreeCouriersWithInterval), ctx)
}

// GetAllCouriers mocks base method.
func (m *MockcourierRepository) GetAllCouriers(ctx context.Context) ([]model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCouriers", ctx)
	ret0, _ := ret[0].([]model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCouriers indicates an expected call of GetAllCouriers.
func (mr *MockcourierRepositoryMockRecorder) GetAllCouriers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCouriers", reflect.TypeOf((*MockcourierRepository)(nil).GetAllCouriers), ctx)
}

// GetCourierById mocks base method.
func (m *MockcourierRepository) GetCourierById(ctx context.Context, id int64) (model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierById", ctx, id)
	ret0, _ := ret[0].(model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierById indicates an expected call of GetCourierById.
func (mr *MockcourierRepositoryMockRecorder) GetCourierById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierById", reflect.TypeOf((*MockcourierRepository)(nil).GetCourierById), ctx, id)
}

// UpdateCourier mocks base method.
func (m *MockcourierRepository) UpdateCourier(ctx context.Context, courier model.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourier", ctx, courier)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourier indicates an expected call of UpdateCourier.
func (mr *MockcourierRepositoryMockRecorder) UpdateCourier(ctx, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourier", reflect.TypeOf((*MockcourierRepository)(nil).UpdateCourier), ctx, courier)
}

// MockdeliveryCalculatorFactory is a mock of deliveryCalculatorFactory interface.
type MockdeliveryCalculatorFactory struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryCalculatorFactoryMockRecorder
}

// MockdeliveryCalculatorFactoryMockRecorder is the mock recorder for MockdeliveryCalculatorFactory.
type MockdeliveryCalculatorFactoryMockRecorder struct {
	mock *MockdeliveryCalculatorFactory
}

// NewMockdeliveryCalculatorFactory creates a new mock instance.
func NewMockdeliveryCalculatorFactory(ctrl *gomock.Controller) *MockdeliveryCalculatorFactory {
	mock := &MockdeliveryCalculatorFactory{ctrl: ctrl}
	mock.recorder = &MockdeliveryCalculatorFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryCalculatorFactory) EXPECT() *MockdeliveryCalculatorFactoryMockRecorder {
	return m.recorder
}

// GetDeliveryCalculator mocks base method.
func (m *MockdeliveryCalculatorFactory) GetDeliveryCalculator(courierType model.CourierTransportType) courier.DeliveryCalculator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliveryCalculator", courierType)
	ret0, _ := ret[0].(courier.DeliveryCalculator)
	return ret0
}

// GetDeliveryCalculator indicates an expected call of GetDeliveryCalculator.
func (mr *MockdeliveryCalculatorFactoryMockRecorder) GetDeliveryCalculator(courierType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliveryCalculator", reflect.TypeOf((*MockdeliveryCalculatorFactory)(nil).GetDeliveryCalculator), courierType)
}
